version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-dev
    container_name: club_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "8000:8000"

  queue:
    <<: *app
    container_name: club_queue
    command: make docker-run-queue
    depends_on:
      - postgres
      - redis
    ports: []

  bot:
    <<: *app
    command: make docker-run-bot
    ports: []
    depends_on:
      - club_app
      - postgres
      - redis

  postgres:
    image: postgres:11
    container_name: club_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  postgres_data:
